### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by chrisagelou** [aueb-cslabs/moniteur-admin#1]
Login fails with error message:
"Error! Λάθος όνομα χρήστη ή κωδικός."

**Comment by root-expert** [comment]
It only works with CSLab private network for now. 
Firewall is down so you can't test 😆

**Comment by enderian** [comment]
🙂

**Comment by chrisagelou** [comment]
Firewall is actually up, and I was using the cslab network.

**Comment by root-expert** [comment]
Check again, server was down

**Comment by chrisagelou** [comment]
still not working

**Comment by MrGoumX** [comment]
:)

**Comment by MrGoumX** [comment]
🙂

**Comment by chrisagelou** [comment]
Api endpoint ip was misconfigured...
After it was changed, it works

**Comment by MrGoumX** [comment]
Added settings functionality in login screen.
